name: CMakeBuilds
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        # do ubuntu specific jobs
        - os: ubuntu-latest

        # do windows specific jobs
        - os: windows-latest

    steps:
    - uses: actions/checkout@v2

    # Configure CMake in a 'build' subdirectory
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build your program with the given configuration
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # create directory for the results
    - name: Create Directory
      working-directory: ${{github.workspace}}/bins
      run: mkdir -p results

    # Execute tests defined by the CMake configuration.  
    - name: Test
      working-directory: ${{github.workspace}}/bins
      run: ctest -C ${{env.BUILD_TYPE}}
    
    # List the all files under the results directory
    - name: List
      working-directory: ${{github.workspace}}/bins/results/
      run: ls -lah
     